### ISSUE TITLE
Please upload 0.1.3 and 0.1.4 to maven central

### ISSUE THREAD

**Issue by blekinge** [web3j/web3j-maven-plugin#11]
As can be seen from here
https://mvnrepository.com/artifact/org.web3j/web3j-maven-plugin
only 0.1.1 and 0.1.2 are in maven central. 
As 0.1.2 generates invalid java files for web3j 3+, this plugin is not very usable.

**Comment by h2mch** [comment]
sorry, i missed the upload part in my release process:
it's now released:
https://oss.sonatype.org/service/local/repositories/releases/content/org/web3j/web3j-maven-plugin/0.1.4/web3j-maven-plugin-0.1.4.jar
