### ISSUE TITLE
Please upload 0.2.0 to maven central

### ISSUE THREAD

**Issue by k06a** [web3j/web3j-maven-plugin#15]

**Comment by h2mch** [comment]
there is no version 0.2.0 yet. The current snapshot is "0.1.5-SNAPSHOT".
When the new version 0.4.19 of ether-camp/solcJ is [available](https://bintray.com/ethereum/maven/org.ethereum.solcJ-all/), I will create a new version.

**Comment by k06a** [comment]
@h2mch saw 0.2.0 in your readme)
