### ISSUE TITLE
No Java 9 compatibility

### ISSUE THREAD

**Issue by Adam6056** [web3j/web3j-maven-plugin#19]
Java 9 mvn web3j:generate-sources throws NullPointerException

![28695751_1669747216423841_899011609_o](https://user-images.githubusercontent.com/11320052/36936338-586018cc-1f04-11e8-9020-2dbc3c0463ac.png)

**Comment by h2mch** [comment]
Should be feîxed with the latest version (0.3.1). At least it works now with Java 10

**Comment by h2mch** [comment]
I personally build with java 10 and have no problems with it. Can you tell me more about your configuration so I can reproduce? (Solidity file, Maven Configuration).
The line of the NullPointer is a commented out Line...
```java
Caused by: java.lang.NullPointerException
at org.web3j.mavenplugin.JavaClassGeneratorMojo.extractContracts (JavaClassGeneratorMojo.java:87)
```

**Comment by Adam6056** [comment]
Hi,
Sorry but this exception not occurs on my PC any more, I have tried on java 9 and 10 SDK and everything is fine.
Settings:
- pragma solidity ^0.4.16;
- Windows 10 
- Maven 3.5.2
- Java 10.0.2
