### ISSUE TITLE
Update to solcJ 0.4.19

### ISSUE THREAD

**Issue by fcorneli** [web3j/web3j-maven-plugin#20]
https://github.com/web3j/web3j-maven-plugin/blob/28b02b8958eaac6458219af4dd6fe224a40a5c28/pom.xml#L71

solcJ 0.4.19 is available.

**Comment by h2mch** [comment]
a new version is created with updated solcJ and web3j libraries
```xml
<dependency>
  <groupId>org.web3j</groupId>
  <artifactId>web3j-maven-plugin</artifactId>
  <version>0.2.0</version>
</dependency>
```

**Comment by fcorneli** [comment]
Using 0.2.0 now, thanks.
