### ISSUE TITLE
Upgrade to web3j 3.5.0

### ISSUE THREAD

**Issue by ice09** [web3j/web3j-maven-plugin#29]
Haven't tried it, but as eg. the default CLI for macos is 3.5.0 and the maven generation still points to 3.4.0, I assume that this might cause errors. At least it was the case with <3.4.0 and CLI 3.4.0.
Anyways, if a CLI version is provided (which is good), it might make sense to also upgrade the other tools using the same class creation and generation functionality.

**Comment by flefevre** [comment]
I have made a very simple PR on this

**Comment by h2mch** [comment]
thx
