### ISSUE TITLE
No plugin found for prefix 'web3j' in the current project

### ISSUE THREAD

**Issue by codebazz** [web3j/web3j-maven-plugin#37]
[INFO] Scanning for projects...
[WARNING] The POM for org.web3j:web3j-maven-plugin:jar:0.3.5-SNAPSHOT is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.web3j:web3j-maven-plugin:0.3.5-SNAPSHOT: Plugin org.web3j:web3j-maven-plugin:0.3.5-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.web3j:web3j-maven-plugin:jar:0.3.5-SNAPSHOT
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 KB at 6.9 KB/sec)
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 KB at 9.9 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.712 s
[INFO] Finished at: 2018-10-07T15:43:01+06:00
[INFO] Final Memory: 9M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'web3j' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\lict\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]

**Comment by h2mch** [comment]
sorry, the "Getting Started" was wrong.
`Snapshot` version are not deployed to the public maven repo. You have to use the `0.3.5` version for now
