### ISSUE TITLE
Option to exclude contracts from source folder

### ISSUE THREAD

**Issue by iikirilov** [web3j/web3j-maven-plugin#39]
There should be something similar to what the gradle plugin can do.

Please see https://github.com/web3j/web3j-gradle-plugin#code-generation

**Comment by h2mch** [comment]
there is/was a "hidding" feature for that, I added the documentation.
see also some testcases [here](https://github.com/web3j/web3j-maven-plugin/tree/master/src/test/projects/filtered)
