### ISSUE TITLE
CANNOT BUILD

### ISSUE THREAD

**Issue by UnforgivenZZZ** [web3j/web3j-maven-plugin#40]
when I build the project followed by the instruction, it shows error: 

mvn web3j:generate-sources
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Malformed POM /Users/jialiang/Desktop/devp/onlinevm/web3j-maven-plugin/pom.xml: Unrecognised tag: 'plugin' (position: START_TAG seen ...</version>\n    <plugin>... @7:13)  @ /Users/jialiang/Desktop/devp/onlinevm/web3j-maven-plugin/pom.xml, line 7, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.web3j:web3j-maven-plugin:0.3.8-SNAPSHOT (/Users/jialiang/Desktop/devp/onlinevm/web3j-maven-plugin/pom.xml) has 1 error
[ERROR]     Malformed POM /Users/jialiang/Desktop/devp/onlinevm/web3j-maven-plugin/pom.xml: Unrecognised tag: 'plugin' (position: START_TAG seen ...</version>\n    <plugin>... @7:13)  @ /Users/jialiang/Desktop/devp/onlinevm/web3j-maven-plugin/pom.xml, line 7, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException

**Comment by h2mch** [comment]
close because of inactivity / no response
