### ISSUE TITLE
Plugin is not compatible with web3j 4

### ISSUE THREAD

**Issue by kelheor** [web3j/web3j-maven-plugin#42]
I updated Web3J library to 4.0.3, then tried to recompile contracts with this plugin, but still getting wrappers for web3j 3.6.0 instead of 4. The problem that those wrappers are incompatible with the latest version of web3j, so I can't update the Web3j library to 4.
Please update this plugin.

**Comment by h2mch** [comment]
Hi kelheoer, i will do it, till end of week

**Comment by kelheor** [comment]
Thanks. I see that you updated it now, but can you also update a plugin in maven repository (the latest version, which is available there is 0.3.7), so I can download it by adding a dependency to .pom file?

**Comment by h2mch** [comment]
it is deployet to sonatype repo. it will take some time to be public available
