### ISSUE TITLE
Plugin now require Java 11 instead of Java 8

### ISSUE THREAD

**Issue by kelheor** [web3j/web3j-maven-plugin#45]
Were there any serious reasons to change Java version from 8 to 11, when Web3j 4 originally supports Java 8?
Now if I want to use your plugin, I have to move from Java 8 to 11, which can potentially cause a lot of issues.
Maybe you can revert it back to 8?

**Comment by kelheor** [comment]
Nevermind. I will update my project to Java 11, maybe it will be better in perspective.

**Comment by ghareeb-falazi** [comment]
We use the plugin for a large project that uses Java 8. Moving to Java 11 is not an option for us at all due to other dependencies. I am in favor of reverting back to 8.

**Comment by fcorneli** [comment]
Could someone release a version of web3j-maven-plugin that still supports Java 8?
There is absolutely no reason to jump to Java 11.
Besides, most Java EE runtimes are still on Java 8...

**Comment by h2mch** [comment]
after more votes/commets for java8, a new version with java 8 is released. includs also newest web3j core version:

https://github.com/web3j/web3j-maven-plugin/releases/tag/web3j-maven-plugin-4.1.0

**Comment by fcorneli** [comment]
@h2mch thanks for the release!

**Comment by fcorneli** [comment]
https://github.com/e-Contract/ethereum-resource-adapter/commit/26af180dd80e942b1393dd18c64d30d4acc0913e
