### ISSUE TITLE
Remove SolcJ dependency and replace with Sokt

### ISSUE THREAD

**Issue by conor10** [web3j/web3j-maven-plugin#53]
We shouldn't be using SolcJ in this plugin - it uses a non-enterprise friendly GPL license. Instead [Sokt](https://github.com/web3j/web3j-sokt) should be used which we already use in the [Solidity Gradle plugin](https://github.com/web3j/solidity-gradle-plugin).

**Comment by xaviarias** [comment]
Fixed in #57
