### ISSUE TITLE
Incorrect Return Type

### ISSUE THREAD

**Issue by chrismcgregor** [web3j/web3j-maven-plugin#55]
I am using Solc v0.6.9 and we I generate the Java code I am getting the incorrect return type for a few of my ERC20 smart contract functions (e.g., balanceOf).

**ERC20 balanceOf function (Solidity code):**

` function balanceOf(address who) external view returns (uint256);`

**Java generated method (returns TransactionReceipt):**
 
`    public RemoteFunctionCall<TransactionReceipt> ERC20BalanceOf(String _erc20Address, String _who) {
        final org.web3j.abi.datatypes.Function function = new org.web3j.abi.datatypes.Function(
                FUNC_ERC20BALANCEOF, 
                Arrays.<Type>asList(new org.web3j.abi.datatypes.Address(160, _erc20Address), 
                new org.web3j.abi.datatypes.Address(160, _who)), 
                Collections.<TypeReference<?>>emptyList());
        return executeRemoteCallTransaction(function);
    }`

**Expected Java generated function (returns BigInteger):**

`public RemoteFunctionCall<BigInteger> ERC20BalanceOf(String _erc20Address, String _who) {
    final org.web3j.abi.datatypes.Function function = new org.web3j.abi.datatypes.Function(
            FUNC_ERC20BALANCEOF,
            Arrays.<Type>asList(new org.web3j.abi.datatypes.Address(160, _erc20Address),
                    new org.web3j.abi.datatypes.Address(160, _who)),
            Arrays.<TypeReference<?>>asList(new TypeReference<Uint256>() {}));
    return executeRemoteCallSingleValueReturn(function, BigInteger.class);
}`

https://ethereum.stackexchange.com/questions/40730/why-is-web3j-java-not-generating-correct-return-types-for-my-contract

**Comment by xaviarias** [comment]
In the Stack Exchange example the function is giving the error because is not a `view`.

Not sure about it but Solidity 0.6.9 but must have a way to mark `balanceOf` as a `view` that has changed from prior versions. 

Could you attach the generated ABI files?

**Comment by chrismcgregor** [comment]
ABI: [Abi.txt](https://github.com/web3j/web3j-maven-plugin/files/4885886/Abi.txt)

Take a look at ERC20BalanceOf() which has a view attribute on the function.

**Comment by joaquin-alfaro** [comment]
From solidity 0.6 the property **constant** included in the ABI has been replaced by the value of **stateMutability** [](https://github.com/ethereum/solidity/issues/8065)

The version _4.5.11_ of **web3j-maven-plugin** uses the value of **constant** to determine if a function is a _view_

You can wait to the version _4.5.18_ of **web3j-maven-plugin** which probably will solve the problem or make a fork of **web3j-maven-plugin** and update the version of **web3j** in pom.xml to _4.5.18_
Replace
<web3j.version>4.5.11</web3j.version>
With
<web3j.version>4.5.18</web3j.version>

**Comment by chrismcgregor** [comment]
Excellent, thank you!

**Comment by chrismcgregor** [comment]
When do you guys plan to release 4.5.18?

**Comment by xaviarias** [comment]
Hi, we just release 4.6.4, can I close this issue?

**Comment by chrismcgregor** [comment]
Absolutely, thank you!

Also, do you know how to generate an Ethereum address from a xpub (extended public key) using Web3j?

Cheers!
Chris

**Comment by xaviarias** [comment]
```java
final String address = org.web3j.crypto.Keys.getAddress("<public key>")
```

**Comment by chrismcgregor** [comment]
Excellent, thank you!

I believe xpub (extended public keys) are Base58 encoded, does org.web3j.crypto.Keys.getAddress("<public key>”) take this into account? I tried the following xpub and it did generate an Ehtereum address, but wanted to make sure of the encoding:

xpub68vRSzZR9TYbhy2EMt8GTem3JPdpd8pLkKWxutr9v3DHV9upZGYH9kWpquYgPyDghzcuRYKKSAC638WdEeq8gmK431NFYbQumxMx4GvhqnB

Cheers!
Chris

**Comment by chrismcgregor** [comment]
I guess my question is that does Keys.getAddress() support BIP32 or other standards?

**Comment by xaviarias** [comment]
> I guess my question is that does Keys.getAddress() support BIP32 or other standards?

Not sure about that, have you tried it? @josh-richardson may have a better answer.

**Comment by chrismcgregor** [comment]
Thank you for the response!

I figured out that the xpub I sent you is a BIP32 extended public key which has a compressed 33 byte key. I noticed that Web3j generates uncompressed public keys 64 bytes. Is there a utility in Web3j to compress/uncompress public keys?
