### ISSUE TITLE
Generation of code fails when using solidity 0.8.0

### ISSUE THREAD

**Issue by joaquin-alfaro** [web3j/web3j-maven-plugin#84]
The generation of source code for smart contracts implemented using solidity 0.8.0 fails.

### Expected behavior
The java classes related with the smart contract are generated in te outputDirectory specified at the pom.xml

### Actual behavior
The java classes are not generated and output of the execution of the plugin shows the following error:

`[ERROR] Failed to execute goal org.web3j:web3j-maven-plugin:4.8.7:generate-sources (default-cli) on project tokenizer: A type incompatibility occurred while executing org.web3j:web3j-maven-plugin:4.8.7:generate-sources: class org.json.simple.JSONArray cannot be cast to class java.lang.String (org.json.simple.JSONArray is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @2216effc; java.lang.String is in module java.base of loader 'bootstrap')`

### Steps to reproduce the behavior
1. Implement an smart contract using solidity 0.8.0
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

/* Example from https://www.ethereum.org/greeter */
contract mortal {
    /* Define variable owner of the type address*/
    address owner;

    /* this function is executed at initialization and sets the owner of the contract */
    constructor () {owner = address(msg.sender);}

    /* Function to recover the funds on the contract */
    function kill() public {if (msg.sender == owner) selfdestruct(payable(owner));}
}
```

2. Execute the generation of java classes
`mvn web3j:generate-sources`

3. The output of the execution of the plugin is
`[ERROR] Failed to execute goal org.web3j:web3j-maven-plugin:4.8.7:generate-sources (default-cli) on project tokenizer: A type incompatibility occurred while executing org.web3j:web3j-maven-plugin:4.8.7:generate-sources: class org.json.simple.JSONArray cannot be cast to class java.lang.String (org.json.simple.JSONArray is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @2216effc; java.lang.String is in module java.base of loader 'bootstrap')`

### Cause of the error
The plugin obtains the **abi** of the smart contract using the option **--combined-json** and expects that the field that contains the abi is a String but since Solidity v0.8.0 this field is a JSON.
Link of the documentation of Solidity explaining the change https://docs.soliditylang.org/en/v0.8.0/080-breaking-changes.html?highlight=combined-json

```
Interface Changes
The output of --combined-json has changed: JSON fields abi, devdoc, userdoc and storage-layout are sub-objects now. Before 0.8.0 they used to be serialised as strings.
The “legacy AST” has been removed (--ast-json on the commandline interface and legacyAST for standard JSON). Use the “compact AST” (--ast-compact--json resp. AST) as replacement.
The old error reporter (--old-reporter) has been removed.
```

**Comment by andrii-kl** [comment]
https://github.com/web3j/web3j-maven-plugin/pull/89

**Comment by errorfourten** [comment]
Will an updated plugin (4.8.8 I assume) be released with this PR any time soon?
