### ISSUE TITLE
doesn't support "pure" and similar newer reserved words

### ISSUE THREAD

**Issue by eepstein** [web3j/web3j-maven-plugin#9]
solc compiles this fine, but the plugin errors out.

Solidity:

```
pragma solidity ^0.4.2;

library ConvertLib{
	function convert(uint amount,uint conversionRate) pure public returns (uint convertedAmount)
	{
		return amount * conversionRate;
	}
}

```

```
[ERROR] Failed to execute goal org.web3j:web3j-maven-plugin:0.1.2:generate-sources (default-cli) on project cannabium-ico: Could not compile solidity files
[ERROR] <stdin>:4:52: Error: Expected token LBrace got reserved keyword 'Pure'
[ERROR] function convert(uint amount,uint conversionRate) pure public returns (uint convertedAmount)

```

**Comment by h2mch** [comment]
Have you used the newest version?
I build your Library with the Plugin and I got following class

`
import java.math.BigInteger;
import java.util.Arrays;
import org.web3j.abi.TypeReference;
import org.web3j.abi.datatypes.Function;
import org.web3j.abi.datatypes.Type;
import org.web3j.abi.datatypes.generated.Uint256;
import org.web3j.crypto.Credentials;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.RemoteCall;
import org.web3j.tx.Contract;
import org.web3j.tx.TransactionManager;

/**
 * <p>Auto generated code.
 * <p><strong>Do not modify!</strong>
 * <p>Please use the <a href="https://docs.web3j.io/command_line.html">web3j command line tools</a>,
 * or the org.web3j.codegen.SolidityFunctionWrapperGenerator in the 
 * <a href="https://github.com/web3j/web3j/tree/master/codegen">codegen module</a> to update.
 *
 * <p>Generated with web3j version 3.0.2.
 */
public final class ConvertLib extends Contract {
    private static final String BINARY = "60606040523415600e57600080fd5b60918061001c6000396000f300606060405260043610603e5763ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166396e4ee3d81146043575b600080fd5b604f6004356024356061565b60405190815260200160405180910390f35b02905600a165627a7a7230582045f242fcdb78c79bf4b320021cff35b79b7c5d5da4ca79d9d2b913ad8429c8290029";

    private ConvertLib(String contractAddress, Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        super(BINARY, contractAddress, web3j, credentials, gasPrice, gasLimit);
    }

    private ConvertLib(String contractAddress, Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        super(BINARY, contractAddress, web3j, transactionManager, gasPrice, gasLimit);
    }

    public RemoteCall<Uint256> convert(Uint256 amount, Uint256 conversionRate) {
        Function function = new Function("convert", 
                Arrays.<Type>asList(amount, conversionRate), 
                Arrays.<TypeReference<?>>asList(new TypeReference<Uint256>() {}));
        return executeRemoteCallSingleValueReturn(function);
    }

    public static RemoteCall<ConvertLib> deploy(Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        return deployRemoteCall(ConvertLib.class, web3j, credentials, gasPrice, gasLimit, BINARY, "");
    }

    public static RemoteCall<ConvertLib> deploy(Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        return deployRemoteCall(ConvertLib.class, web3j, transactionManager, gasPrice, gasLimit, BINARY, "");
    }

    public static ConvertLib load(String contractAddress, Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        return new ConvertLib(contractAddress, web3j, credentials, gasPrice, gasLimit);
    }

    public static ConvertLib load(String contractAddress, Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        return new ConvertLib(contractAddress, web3j, transactionManager, gasPrice, gasLimit);
    }
}
`

**Comment by h2mch** [comment]
Okay. found the issue. The solidity version inside ethereumj library is a bit too old.

To get ride of that, you have to install the solidity compiler (solc) locally. At least as long as the ethereumj library is not updated with the new solc compiler.

When solidity is on the systempath, the maven plugin will automatically take that version.
```
C:\...>solc --version
solc, the solidity compiler commandline interface
Version: 0.4.18+commit.9cf6e910.Windows.msvc
```
